Pretrained Masked Language Model

In [38]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

#MODEL_TYPE = "prajjwal1/bert-tiny"
MODEL_TYPE = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(MODEL_TYPE)

tokenizer.vocab_size


30522

In [39]:
texts = [
    ("After Abraham Lincoln won the November 1860 presidential "
     "election on an anti-slavery platform, an initial seven "
     "slave states declared their secession from the country "
     "to form the Confederacy. War broke out in April 1861 "
     "when secessionist forces attacked Fort Sumter in South "
     "Carolina, just over a month after Lincoln's "
     "[MASK]."),
    ("In response to Lincoln's election, seven Southern states "
     "seceded from the Union and formed the Confederate States "
     "of America. These states were South Carolina, Mississippi, "
     "Florida, Alabama, Georgia, Louisiana, and Texas. The "
     "secession of these states was a direct challenge to the "
     "authority of the federal government and set the stage for "
     "the Civil [MASK]."),
]


In [40]:
inputs = tokenizer(texts, 
                   padding=True,
                   return_tensors='pt')
type(inputs)


transformers.tokenization_utils_base.BatchEncoding

In [29]:
inputs.keys()


dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [41]:
inputs["input_ids"]


tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055,   103,
          1012,   102,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1999,  3433,  2000,  5367,  1005,  1055,  2602,  1010,  2698,
          2670,  2163, 10819, 19082,  2013,  1996,  2586,  1998,  2719,  1996,
          8055,  2163,  1997,  2637,  1012,  2122,  2163,  2020,  2148,  3792,
          1010,  5900,  1010,  3516,  1010,  6041,  1010,  4108,  1010,  5773,
          1010,  1998,  3146,  1012,  1996, 22965,  1997,  2122,  2163,  2001,
          1037,  3622,  4119,  2000,  1996,  3691, 

In [6]:
type(inputs["input_ids"])


torch.Tensor

In [7]:
inputs['labels'] = inputs.input_ids.detach().clone()


In [8]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

In [30]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055,   103,
          1012,   102,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1999,  3433,  2000,  5367,  1005,  1055,  2602,  1010,  2698,
          2670,  2163, 10819, 19082,  2013,  1996,  2586,  1998,  2719,  1996,
          8055,  2163,  1997,  2637,  1012,  2122,  2163,  2020,  2148,  3792,
          1010,  5900,  1010,  3516,  1010,  6041,  1010,  4108,  1010,  5773,
          1010,  1998,  3146,  1012,  1996, 22965,  1997,  2122,  2163,  2001,
          1037,  3622,  4119,  2000, 

In [31]:
inputs["input_ids"].shape

torch.Size([2, 70])

In [42]:
from transformers import BertModel
from transformers import BertForMaskedLM

model = BertForMaskedLM.from_pretrained(MODEL_TYPE)


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [43]:
output = model(
    input_ids=inputs["input_ids"],
    token_type_ids=inputs["token_type_ids"],
    attention_mask=inputs["attention_mask"])


In [44]:
output

MaskedLMOutput(loss=None, logits=tensor([[[ -8.2426,  -8.2028,  -8.2557,  ...,  -7.2883,  -7.3752,  -5.1033],
         [-12.1989, -12.0338, -12.2798,  ..., -11.5445, -11.1747,  -8.9771],
         [ -7.0761,  -7.1125,  -6.6490,  ...,  -6.5038,  -7.1784,  -5.4737],
         ...,
         [ -6.3599,  -6.8373,  -6.5935,  ...,  -4.8487,  -6.6077,  -6.9051],
         [ -3.3518,  -4.0345,  -3.3448,  ...,  -2.6487,  -4.2840,  -4.2557],
         [ -4.1612,  -4.8025,  -4.1519,  ...,  -3.4086,  -4.8660,  -5.3375]],

        [[ -7.6152,  -7.6263,  -7.6300,  ...,  -6.8500,  -6.8573,  -4.5814],
         [-17.0938, -17.0038, -17.3263,  ..., -14.5825, -14.6042, -12.8379],
         [ -5.0147,  -4.7896,  -5.4301,  ...,  -4.7335,  -5.2917,  -3.1833],
         ...,
         [ -2.9033,  -2.5517,  -3.0579,  ...,  -0.9628,  -2.7572,  -3.4291],
         [-14.2287, -14.2686, -14.2860,  ..., -11.8868, -11.9608,  -9.9601],
         [-10.1814, -10.7392, -10.2036,  ...,  -9.8099,  -7.6379,  -8.2945]]],
       grad

In [37]:
output.keys()

odict_keys(['logits'])

In [15]:
output.last_hidden_state.shape

torch.Size([2, 70, 128])

In [16]:
output.pooler_output.shape

torch.Size([2, 128])

In [17]:
test_texts = [
    ("Abraham Lincoln was the 16th President of the United States, serving from "
     "1861 until his assassination in 1865. He is widely considered to be one "
     "of the most important and influential figures in American history, "
     "particularly for his role in leading the country through the Civil War "
     "and for his efforts to abolish slavery."),
     ("Lincoln was born on February 12, "
     "1809, in Hodgenville, Kentucky. He grew up in poverty and received only a "
     "limited formal education. Nevertheless, he taught himself law and became "
     "a successful lawyer before entering politics. He served in the Illinois "
     "legislature and in the U.S. House of Representatives before being elected "
     "president in 1860."),
]

test_inputs = tokenizer(test_texts,
                        padding=True,
                        return_tensors='pt')


In [18]:
test_inputs["input_ids"].shape

torch.Size([2, 69])

In [19]:
test_output = model(
    input_ids=test_inputs["input_ids"],
    token_type_ids=test_inputs["token_type_ids"],
    attention_mask=test_inputs["attention_mask"])

test_output.last_hidden_state.shape

torch.Size([2, 69, 128])

User Profile

In [20]:
import torch

user_profiles = torch.Tensor([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [1.0, 2.0, 3.0, 4.0, 5.0]])

user_profiles.shape


torch.Size([2, 5])

Predict Masked Words

In [21]:
import torch

batch_size = output.last_hidden_state.size()[0]
sequence_len = output.last_hidden_state.size()[1]

user_profiles = torch.reshape(
    input=user_profiles, shape=(batch_size, 1, 5))
user_profiles_cloned = user_profiles.repeat(
    repeats=(1, sequence_len, 1))


all_features = torch.concatenate(
    (user_profiles_cloned, output.last_hidden_state), dim=2)

all_features

tensor([[[ 0.1000,  0.2000,  0.3000,  ..., -0.9320, -0.6556,  1.8571],
         [ 0.1000,  0.2000,  0.3000,  ..., -1.7244, -0.7812,  0.5787],
         [ 0.1000,  0.2000,  0.3000,  ..., -2.1885, -0.9960,  2.9772],
         ...,
         [ 0.1000,  0.2000,  0.3000,  ..., -1.0744, -0.0773,  1.9667],
         [ 0.1000,  0.2000,  0.3000,  ..., -0.7104, -0.1538,  1.6433],
         [ 0.1000,  0.2000,  0.3000,  ..., -0.7003, -0.2023,  1.6985]],

        [[ 1.0000,  2.0000,  3.0000,  ..., -0.5218, -1.3571,  2.4143],
         [ 1.0000,  2.0000,  3.0000,  ..., -2.1451, -0.7536,  1.1829],
         [ 1.0000,  2.0000,  3.0000,  ..., -1.7277, -1.7523,  2.3260],
         ...,
         [ 1.0000,  2.0000,  3.0000,  ..., -1.0819, -0.8957,  0.4729],
         [ 1.0000,  2.0000,  3.0000,  ..., -0.7759, -0.8671,  0.5607],
         [ 1.0000,  2.0000,  3.0000,  ..., -1.1317, -0.9062,  1.0917]]],
       grad_fn=<CatBackward0>)

In [22]:
linear = torch.nn.Linear(
    in_features=128 + 5, out_features=tokenizer.vocab_size)
softmax = torch.nn.Softmax(dim=1)

h_transformed = linear(all_features)
preds = softmax(h_transformed)

preds


tensor([[[0.0159, 0.0175, 0.0113,  ..., 0.0113, 0.0178, 0.0116],
         [0.0213, 0.0075, 0.0087,  ..., 0.0191, 0.0092, 0.0125],
         [0.0161, 0.0112, 0.0111,  ..., 0.0138, 0.0103, 0.0126],
         ...,
         [0.0175, 0.0066, 0.0173,  ..., 0.0178, 0.0116, 0.0123],
         [0.0174, 0.0079, 0.0169,  ..., 0.0177, 0.0117, 0.0115],
         [0.0152, 0.0078, 0.0144,  ..., 0.0173, 0.0101, 0.0121]],

        [[0.0188, 0.0187, 0.0110,  ..., 0.0093, 0.0235, 0.0112],
         [0.0124, 0.0074, 0.0237,  ..., 0.0154, 0.0083, 0.0079],
         [0.0239, 0.0160, 0.0136,  ..., 0.0063, 0.0181, 0.0154],
         ...,
         [0.0220, 0.0062, 0.0179,  ..., 0.0199, 0.0181, 0.0095],
         [0.0134, 0.0088, 0.0132,  ..., 0.0263, 0.0077, 0.0155],
         [0.0164, 0.0072, 0.0188,  ..., 0.0128, 0.0102, 0.0248]]],
       grad_fn=<SoftmaxBackward0>)

In [23]:
preds.shape


torch.Size([2, 70, 30522])