Pretrained Masked Language Model

In [1]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

# prajjwal1/bert-tiny
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")


2023-03-29 20:32:26.921875: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-29 20:32:27.001244: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-29 20:32:27.001257: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-03-29 20:32:27.566320: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [2]:
texts = [
    ("After Abraham Lincoln won the November 1860 presidential "
     "election on an anti-slavery platform, an initial seven "
     "slave states declared their secession from the country "
     "to form the Confederacy. War broke out in April 1861 "
     "when secessionist forces attacked Fort Sumter in South "
     "Carolina, just over a month after Lincoln's "
     "inauguration."),
    ("In response to Lincoln's election, seven Southern states "
     "seceded from the Union and formed the Confederate States "
     "of America. These states were South Carolina, Mississippi, "
     "Florida, Alabama, Georgia, Louisiana, and Texas. The "
     "secession of these states was a direct challenge to the "
     "authority of the federal government and set the stage for "
     "the Civil War.")
]


In [3]:
inputs = tokenizer(texts, padding=True, return_tensors='pt')


In [4]:
inputs.keys()


dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [5]:
inputs


{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1999,  3433,  2000,  5367,  1005,  1055,  2602,  1010,  2698,
          2670,  2163, 10819, 19082,  2013,  1996,  2586,  1998,  2719,  1996,
          8055,  2163,  1997,  2637,  1012,  2122,  2163,  2020,  2148,  3792,
          1010,  5900,  1010,  3516,  1010,  6041,  1010,  4108,  1010,  5773,
          1010,  1998,  3146,  1012,  1996, 22965,  1997,  2122,  2163,  2001,
          1037,  3622,  4119,  2000, 

In [6]:
inputs['labels'] = inputs.input_ids.detach().clone()


In [7]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])

In [8]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,  2000,  2433,
          1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,  6863,  2043,
         22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,  2148,  3792,
          1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,  1055, 17331,
          1012,   102,     0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1999,  3433,  2000,  5367,  1005,  1055,  2602,  1010,  2698,
          2670,  2163, 10819, 19082,  2013,  1996,  2586,  1998,  2719,  1996,
          8055,  2163,  1997,  2637,  1012,  2122,  2163,  2020,  2148,  3792,
          1010,  5900,  1010,  3516,  1010,  6041,  1010,  4108,  1010,  5773,
          1010,  1998,  3146,  1012,  1996, 22965,  1997,  2122,  2163,  2001,
          1037,  3622,  4119,  2000, 

In [9]:
rand = torch.rand(inputs.input_ids.shape)
mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
mask_arr


tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False,  True,
         False, False, False, False, False, False, False, False, False, False,
         False, False,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False,  True,  True,
         False, False, False,  True, False, False,  True, False, False, False],
        [False, False, False, False, False,  True, False, False, False,  True,
         False, False, False, False,  True, False, False,  True, False, False,
          True, False, False, False,  True, False, False, False, False,  True,
         False, False,  True, False, False,  True, False, False, False, False,
         False, False, False, False,  True, False, False,  True, False, False,
         False, False, False, False, False, False, 

In [10]:
inputs["input_ids"].shape

torch.Size([2, 70])

In [11]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-uncased")


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [12]:
output = model(
    input_ids=inputs["input_ids"],
    token_type_ids=inputs["token_type_ids"],
    attention_mask=inputs["attention_mask"])


In [13]:
output.last_hidden_state.shape

torch.Size([2, 70, 768])

In [14]:
output.pooler_output.shape

torch.Size([2, 768])

User Profile

In [15]:
import torch

user_profiles = torch.Tensor([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [1.0, 2.0, 3.0, 4.0, 5.0]])

user_profiles.shape


torch.Size([2, 5])

Predict Masked Words

In [16]:
import torch

batch_size = output.last_hidden_state.size()[0]
sequence_len = output.last_hidden_state.size()[1]

user_profiles = torch.reshape(
    input=user_profiles, shape=(batch_size, 1, 5))
user_profiles_cloned = user_profiles.repeat(
    repeats=(1, sequence_len, 1))


all_features = torch.concatenate(
    (user_profiles_cloned, output.last_hidden_state), dim=2)

all_features

tensor([[[ 0.1000,  0.2000,  0.3000,  ..., -0.5229,  0.0727,  0.4822],
         [ 0.1000,  0.2000,  0.3000,  ..., -0.6454, -0.1276,  0.3828],
         [ 0.1000,  0.2000,  0.3000,  ..., -0.3775, -0.0720,  0.7561],
         ...,
         [ 0.1000,  0.2000,  0.3000,  ...,  0.0268, -0.2146,  0.1057],
         [ 0.1000,  0.2000,  0.3000,  ...,  0.0059, -0.2434,  0.3223],
         [ 0.1000,  0.2000,  0.3000,  ..., -0.0615, -0.1829,  0.4679]],

        [[ 1.0000,  2.0000,  3.0000,  ..., -0.3774,  0.0676,  0.3794],
         [ 1.0000,  2.0000,  3.0000,  ..., -0.4656,  0.1010,  0.4625],
         [ 1.0000,  2.0000,  3.0000,  ..., -0.6897, -0.6790,  0.2936],
         ...,
         [ 1.0000,  2.0000,  3.0000,  ..., -1.0303, -0.0412,  0.7372],
         [ 1.0000,  2.0000,  3.0000,  ...,  0.2470, -0.4527, -0.2162],
         [ 1.0000,  2.0000,  3.0000,  ..., -0.3900, -0.5209,  0.2052]]],
       grad_fn=<CatBackward0>)

In [17]:
linear = torch.nn.Linear(
    in_features=768 + 5, out_features=tokenizer.vocab_size)
softmax = torch.nn.Softmax(dim=1)

h_transformed = linear(all_features)
preds = softmax(h_transformed)

preds


tensor([[[0.0126, 0.0148, 0.0228,  ..., 0.0140, 0.0146, 0.0186],
         [0.0124, 0.0084, 0.0138,  ..., 0.0183, 0.0210, 0.0225],
         [0.0112, 0.0236, 0.0134,  ..., 0.0158, 0.0187, 0.0153],
         ...,
         [0.0176, 0.0135, 0.0140,  ..., 0.0164, 0.0139, 0.0120],
         [0.0158, 0.0128, 0.0136,  ..., 0.0148, 0.0140, 0.0132],
         [0.0161, 0.0122, 0.0130,  ..., 0.0145, 0.0139, 0.0137]],

        [[0.0138, 0.0142, 0.0238,  ..., 0.0154, 0.0198, 0.0195],
         [0.0101, 0.0096, 0.0156,  ..., 0.0142, 0.0152, 0.0186],
         [0.0081, 0.0079, 0.0133,  ..., 0.0184, 0.0141, 0.0150],
         ...,
         [0.0144, 0.0111, 0.0134,  ..., 0.0167, 0.0176, 0.0181],
         [0.0202, 0.0094, 0.0128,  ..., 0.0090, 0.0120, 0.0117],
         [0.0076, 0.0144, 0.0108,  ..., 0.0069, 0.0124, 0.0127]]],
       grad_fn=<SoftmaxBackward0>)

In [18]:
preds.shape


torch.Size([2, 70, 30522])